name: Shell Commands
on: [push]
jobs:
  run-shell-command:
    run-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "hello there!!" 
      - name: multline-script
        run: |
          node -v
          npm -v
          echo "node version is diplayed"
        