name: Shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "hello there!!" 
      - name: multline-script
        run: |
          node -v
          npm -v
<<<<<<< HEAD
          echo "node version is diplayed"
        
=======
        
>>>>>>> 74d21356a0a1963b3a9b82e72d1904e782e4118d
