name: Shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "hello there!!" 
      - name: multline-script
        run: |
          node -v
          npm -v
          echo "node version is diplayed"
      - name: python command 
        run: | 
          import platform
          print(platform.processor())
        shell: python
        
